Post transactions
Kalololol/ForexApp pull request #2
Opened 2023-11-17 15:40 UTC by Kalololol

Please, look at the class CalculateTransaction and parametr valuePLN. 
whether to provide a condition if null?

 if(valuePLN == null || valuePLN == 0.00) - is this ok ?

2023-11-17 16:56 UTC, blazejprzyluski requested changes

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CSVMapper.java
> +            throw new RuntimeException(e);
Please provide a descriptive information what went wrong

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CSVMapper.java
> +    public ArrayList<Transaction> readingFromFile(String fileName){
Better convention is to return List interface instead of implementation

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CSVMapper.java
> +        ArrayList<String> arrayFromFile = new ArrayList();
List

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CSVMapper.java
> +        ArrayList<Transaction> transactionArrayList = new ArrayList<>();
List

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CSVMapper.java
> +                Transaction transaction = new Transaction(date, lineFromArray[1], valueCurrency);
No need to create an intermediate field, you can add a transaction straight to the list

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    private CurrencyDownloadApi currencyDownloadApi = new CurrencyDownloadApi();
final

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    private JsonMapper jsonMapper = new JsonMapper();
final

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +            Transaction transaction =  new Transaction(date, codeCurrency, valueTransaction, 0.00, 0.00, false);;
double space after "="

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    public ArrayList<Transaction> TransactionList(ArrayList<Transaction> transactionArrayList){
transactionList -> camelCase

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    public ArrayList<Transaction> TransactionList(ArrayList<Transaction> transactionArrayList){
return List interface instead of implementation

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +        return transaction;
No need for object creation at line 26, you can just return the new transaction

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    public ArrayList<Transaction> TransactionList(ArrayList<Transaction> transactionArrayList){
What is purpose of this function at all? IMO to be deleted

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    public double CalculateValue(String codeCurrency, String dateTransaction){
camelCase naming
make it private if not used outside of this class
what type of value is being calculated?

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    public double percentageResult(ArrayList<Transaction> transactionArrayList){
make private, accept List interface instead of implementation

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +        return average;
you can just return here the result here of line 74, average is obsolete

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +        average = sum / transactionArrayList.size() * 100;
shouldn't the multiplication be in parentheses?

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/model/Currency.java
> +
unnecessary white space

2023-11-17 16:56 UTC, blazejprzyluski commented on src/main/java/model/Transaction.java
> +//    public Transaction(LocalDate dateTransaction, String codeCurrency, double valueCurrency, double valuePln, double resultTransaction) {
To be deleted

2023-11-18 08:11 UTC, Kalololol commented on src/main/java/logic/CSVMapper.java
> +            throw new RuntimeException(e);
is the comparison condition correct?
if(valuePLN == null || valuePLN == 0.00)

2023-11-18 08:12 UTC, Kalololol commented on src/main/java/logic/CSVMapper.java
> +                Transaction transaction = new Transaction(date, lineFromArray[1], valueCurrency);
good point

2023-11-18 08:14 UTC, Kalololol commented on src/main/java/logic/CalculateTransaction.java
> +            Transaction transaction =  new Transaction(date, codeCurrency, valueTransaction, 0.00, 0.00, false);;
Why double space after "="?

2023-11-18 08:19 UTC, Kalololol commented on src/main/java/logic/CalculateTransaction.java
> +    public ArrayList<Transaction> TransactionList(ArrayList<Transaction> transactionArrayList){
CSVMapper read and save object and this method read list object, calculate result and save on list

2023-11-18 08:20 UTC, Kalololol commented on src/main/java/logic/CalculateTransaction.java
> +        return transaction;
ok, correct
delete line 26 and 28 and add this:
        return new Transaction(date, codeCurrency, valueTransaction, valuePLN, convertTransaction, true);

2023-11-18 08:23 UTC, Kalololol commented on src/main/java/logic/CalculateTransaction.java
> +    public double CalculateValue(String codeCurrency, String dateTransaction){
I refactor name 
new name is convertCurrency

2023-11-18 08:25 UTC, Kalololol commented on src/main/java/logic/CalculateTransaction.java
> +    public double percentageResult(ArrayList<Transaction> transactionArrayList){
I wonder if it should be private.
I don't know where to use it yet

2023-11-18 08:44 UTC, Kalololol commented on src/main/java/logic/CalculateTransaction.java
> +        average = sum / transactionArrayList.size() * 100;
my mistake, correct (a / b) * c

2023-11-18 08:49 UTC, Kalololol commented
Code is corrected, please feedback

2023-11-20 13:36 UTC, blazejprzyluski commented on src/main/java/logic/CSVMapper.java
> +            throw new RuntimeException(e);
If there is a null check then it shouldn't compare for a value. Is there a possibility of 0.00 value of transaction? IMO it is a valid case to handle.

2023-11-20 13:37 UTC, blazejprzyluski commented on src/main/java/logic/CalculateTransaction.java
> +    public double percentageResult(ArrayList<Transaction> transactionArrayList){
If a method is used in a single class, always make it private. Only extend the privacy when properly motivated to do so.

2023-11-20 13:41 UTC, blazejprzyluski commented
Overall, the naming of the commits is not descriptive. When looking at the history it will be very confusing. Would you like to fix it or will it be OK for you to just add more descriptive commit messages moving forward?

2023-11-21 13:29 UTC, merged